[package]
name = "rdns_daemon"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
async-std = { version = "1.6.5", features = ["attributes"] }

log = "0.4.11"
loggify = "1.0.0"
rdns_proto = { path = "../proto" }
yaml-rust = "0.4.2"