[package]
name = "rdns_daemon"
version = "0.1.0"
authors = ["lholznagel <contact@lholznagel.info>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
log = "0.4.6"
loggify = "1.0.0"
mio = "0.6.16"
rdns_proto = { path = "../proto" }
yaml-rust = "0.4.2"